### ISSUE TITLE
Communication between sticks

### ISSUE THREAD

**Issue by PaMuGa** [PaMuGa/Frackstock#5]
How should we implement the communication between different sticks?

- BLE Advertising / Scan
- Smartphone (slow, easy)

**Comment by ArberMataj** [comment]
broadcast over advertising -> all sticks will glow the same

**Comment by PaMuGa** [comment]
So, we need to implement a second advertising configuration and an advertising listener. How can we define, which one is the master?

**Comment by PaMuGa** [comment]
Or could we implement a time synchronisation via Smartphone and RTC? Could be easier to implement and there is no dependency of a "good" connection between the sticks.

**Comment by PaMuGa** [comment]
Approach with BLE Advertising / Scan seems to work. Tested with an iBeacon advertising packet. Trying to improve packet structure.

**Comment by Appalco** [comment]
Wow nice work.
Well done

**Comment by PaMuGa** [comment]
Synchronisation is performing well. I will commit the actual version today. However the patterns need to be implemented quite good for good synchronisation.
