### ISSUE TITLE
LED patterns testing

### ISSUE THREAD

**Issue by PaMuGa** [PaMuGa/Frackstock#8]
Most patterns aren't working at the moment. Need to test and fix them for final firmware version.

Working patterns:
- Purple Rain (could be improved)
- Color
- Reset

Not working:
- Remaining

White Flash / Flash is maybe taking to much current --> voltage drop --> reset.

Would also be nice to add some more...

**Comment by Appalco** [comment]
Nice work.
I will test my patterns tuesday evening at 19.30.

**Comment by Appalco** [comment]
**Update New Patterns 16.10.2018 00:37

New Working patterns:

- White Flash
- Flash
- Colorfull


Not working:
- Shift (Need to implement a shift register)
- Rainbow (hsv conversion create a step, maybe combine with Flash???)

New Ideas:

- Combining flash with accelerator (Is the sensor now death?)

**Comment by PaMuGa** [comment]
Did you define an abs(x) function somewhere? Couldn't find one, but there is one needed für HSV convertion.

**Comment by PaMuGa** [comment]
Implemented new:
- Sparkling Red

Bug fixed for:
- Rainbow
- Colorful

Accelerometer isn't implemented in actual release for Frackwoche 2018. The ic isn't woking on all boards. Could be repaired and implemented for Nacht der Technik.

**Comment by Appalco** [comment]
Implemented new:

    Flashcolor
    Shift

**Comment by PaMuGa** [comment]
All patterns tested and fixed.
