### ISSUE TITLE
LED Patterns that use too much current are reseting the NRF 52

### ISSUE THREAD

**Issue by Appalco** [PaMuGa/Frackstock#9]
**Describe the bug**
NRF52 is resetting when all LEDs are shining on high brightness

**FAST FIX**
Added a #DEFINE BRIGHTNESSS 80 for LED patterns which drawn too much current.

**Testing**
How much brightness can we use on low battery? Need to be tested!

**Comment by PaMuGa** [comment]
Test with new batteries, the actual used cell in the prototype isn't able to provide enough current.

**Comment by PaMuGa** [comment]
The new cells are able to provide more current, but the limitation is still active. Otherwise, the batteries would discharge to fast.
